More script updates

diff --git a/developers/GenerateTable b/developers/GenerateTable
--- a/developers/GenerateTable
+++ b/developers/GenerateTable
@@ -119,7 +119,22 @@ EOF
 oldskip=""
 oldlist="v0.02 v0.03 v0.04 v0.05 v0.06 v0.07 v0.08 v0.09 v0.10 v0.11 v0.12 v0.13 v0.14"
 
+# Pre-checkout
+for oldrel in $oldlist; do
+    skip=`contains $oldrel $oldskip`
+    if [ "y" == "$skip" ]; then
+        echo "Skipping version $oldrel"
+        continue
+    fi
+    if git checkout origin/releases/$oldrel; then
+        echo "Checkout of $oldrel succeeded"
+    else
+        echo "Checkout of $oldrel failed"
+        exit 1
+    fi
+done
 
+# Checkout and build
 for oldrel in $oldlist; do
     skip=`contains $oldrel $oldskip`
     if [ "y" == "$skip" ]; then
