Added skip lists

diff --git a/developers/GenerateTable b/developers/GenerateTable
--- a/developers/GenerateTable
+++ b/developers/GenerateTable
@@ -1,5 +1,23 @@
 #!/bin/bash
 #
+
+#
+# Arg1: item to search for
+# Remaining args: list
+#
+contains()
+{
+    key=$1
+    shift
+    for args; do
+        if [ "$key" == "$args" ]; then
+            echo "y"
+            return
+        fi
+    done
+    echo "n"
+}
+
 # Builds a table of run times for various versions of Meddly.
 # The different versions are obtained from the git repository.
 # Compiles each version, runs the benchmark script, and
@@ -7,13 +25,13 @@
 #
 
 if [ $# -ne "1" ]; then
-  echo "Usage: $0 <file.html>"
-  exit 1
+    echo "Usage: $0 <file.html>"
+    exit 1
 fi
 
 if [ ! -f autogen.sh ]; then
-  echo "Are you running this in the Meddly root directory?"
-  exit 1
+    echo "Are you running this in the Meddly root directory?"
+    exit 1
 fi
 
 OUT="`pwd`/$1"
@@ -96,46 +114,61 @@ EOF
 
 #
 # Old releases - are branches
+# oldskip - versions to skip for various reasons
 #
+oldskip="v0.02"
+oldlist="v0.02 v0.03 v0.04 v0.05 v0.06 v0.07 v0.08 v0.09 v0.10 v0.11 v0.12 v0.13 v0.14"
 
-for oldrel in v0.02 v0.03 v0.04 v0.05 v0.06 v0.07 v0.08 v0.09 v0.10 v0.11 v0.12 v0.13 v0.14; do
-  if git checkout origin/releases/$oldrel; then
-    echo "Checkout of $oldrel succeeded"
-  else
-    echo "Checkout of $oldrel failed"
-    exit 1
-  fi
-  ./autogen.sh
-  if make clean all check; then
-    echo "Build of version $oldrel succeeded"
-  else
-    echo "Build of version $oldrel failed"
-    exit 1
-  fi
-  ./RunBenchmarks -h $OUT
+
+for oldrel in $oldlist; do
+    skip=`contains $oldrel $oldskip`
+    if [ "y" == "$skip" ]; then
+        echo "Skipping version $oldrel"
+        continue
+    fi
+    if git checkout origin/releases/$oldrel; then
+        echo "Checkout of $oldrel succeeded"
+    else
+        echo "Checkout of $oldrel failed"
+        exit 1
+    fi
+    ./autogen.sh
+    if make clean all check; then
+        echo "Build of version $oldrel succeeded"
+    else
+        echo "Build of version $oldrel failed"
+        exit 1
+    fi
+    ./RunBenchmarks -h $OUT
 done
 
 #
 # New releases
+# newskip - versions to skip for various reasons
 #
-
+newskip=""
 newlist=`git tag | xargs`
 
 for newrel in $newlist master; do
-  if git checkout $newrel; then
-    echo "Checkout of $newrel succeeded"
-  else
-    echo "Checkout of $newrel failed"
-    exit 1
-  fi
-  ./autogen.sh
-  if make clean all check; then
-    echo "Build of version $newrel succeeded"
-  else
-    echo "Build of version $newrel failed"
-    exit 1
-  fi
-  ./RunBenchmarks -h $OUT
+    skip=`contains $newrel $newskip`
+    if [ "y" == "$skip" ]; then
+        echo "Skipping version $newrel"
+        continue
+    fi
+    if git checkout $newrel; then
+        echo "Checkout of $newrel succeeded"
+    else
+        echo "Checkout of $newrel failed"
+        exit 1
+    fi
+    ./autogen.sh
+    if make clean all check; then
+        echo "Build of version $newrel succeeded"
+    else
+        echo "Build of version $newrel failed"
+        exit 1
+    fi
+    ./RunBenchmarks -h $OUT
 done
 
 
